### ISSUE TITLE
게시판 no의 숫자

### ISSUE THREAD

**Issue by JunHyeongJeon** [ssu-see/see.ssu.ac.kr#13]
게시판 no의 숫자가 역순입니다.

통상적으로 새로운글의 숫자가 더 높다고 알고있습니다.

**Comment by wikibootup** [comment]
좋은 이슈 감사합니다.
이 부분은 @Luavis 님이 해주시면 좋을 것 같습니다. (링크보드 역시 똑같은 방식으로 no 적용이 되어있어서 같이 수정 부탁드립니다.)

**Comment by wikibootup** [comment]
이부분은 제가 리팩토링중에 적용했습니다. @JunHyeongJeon 또 이슈 있으면 많이 남겨주시면 감사하겠습니다.

![screen shot 2015-04-01 at 4 56 24 am](https://cloud.githubusercontent.com/assets/6479173/6927971/eb5eac10-d82b-11e4-8ec5-913f20d4d2de.png)
