### ISSUE TITLE
로그인/아웃 성공/실패 메세지

### ISSUE THREAD

**Issue by JunHyeongJeon** [ssu-see/see.ssu.ac.kr#15]
로그인/아웃 성공/실패 메세지 즉, <SUCCESS : Logout Successfully Logout> 가 나타남으로써, 잠시동안이지만, 메세지가 가려서 원하는 보드로 바로 접근할수 없음.

-요약 : 메세지 팝업이 보드 버튼을 가림.

**Comment by wikibootup** [comment]
그부분은 원래 팝업이 2초였는데, @Luavis 님이 5초로 수정해두었습니다. 

제 생각에 그 이유는 처음 홈페이지를 사용하는 사람들이 읽기엔 2초가 짧아서인게 아닐까 생각해보았습니다.
다시 3초로 수정해두겠습니다.

**Comment by wikibootup** [comment]
3초로 수정했는데, 이것도 좀 긴것같다는 생각이 드네요, 더 짧게 해야한다면 이슈 부탁드립니다, 우선 클로즈하겠습니다
