### ISSUE TITLE
게시판의 글게시권한과 댓글게시권한의 분리

### ISSUE THREAD

**Issue by JunHyeongJeon** [ssu-see/see.ssu.ac.kr#39]
게시판의 글게시권한과 댓글게시권한의 분리가 필요한듯합니다

**Comment by wikibootup** [comment]
옙 의견 감사합니다. 저는 지금 당장은 수정하기 어려울것같고, 4월 말 전후로 점검해보겠습니다

**Comment by wikibootup** [comment]
방금(25일 오전 4시) 분리하였습니다. 클로즈 하겠습니다
