### ISSUE TITLE
링크게시판 수정해야할 내용

### ISSUE THREAD

**Issue by wikibootup** [ssu-see/see.ssu.ac.kr#42]
- [x] pagenate_by 10으로 수정 
- [ ] 테이블 td 수정 ( edit, delete가 나오는게 안 예쁨 )

**Comment by Luavis** [comment]
쫌 적당한 라이브러리를 찾아서 수정할 예정입니다.

**Comment by wikibootup** [comment]
넵 알겠습니다

**Comment by wikibootup** [comment]
1. 그런데 이런 링크게시판과 같은 형태의 라이브러리가 있나요?
2. 게시판 관련 라이브러리를 말하는건가요?
(디비 구조까지 싹 바뀌는?)

잘하시니까 문제는 없겠지만
만약 게시판 디비 구조까지 바꿔야 하면
조금은 신중해야겠네요

그렇지만 직접 구현할 코드가 줄어든다면, 대찬성입니다

**Comment by Luavis** [comment]
구현했습니다

**Comment by wikibootup** [comment]
역시,, 깔끔하고 이쁘네요

감사합니다
