### ISSUE TITLE
마이그레이션 파일

### ISSUE THREAD

**Issue by wikibootup** [ssu-see/see.ssu.ac.kr#46]
프로그램의 수정이 자주 되고 있어서 마이그레이션 파일이 지저분해지는 것 같습니다.
지금은 ignore 상태입니다.

프로그램이 안정화 된 뒤에 ignore에서 빼도록 하겠습니다.

**Comment by Luavis** [comment]
왠만하면 migration 파일은 포함해주세요. 테스팅하는데 버그가 납니다....ㅠ

**Comment by wikibootup** [comment]
어떤 테스트를 할때 문제가 생기던가요?

**Comment by Luavis** [comment]
DB 파일이 생성이 안됩니다

**Comment by wikibootup** [comment]
```python
$ python manage.py makemigrations <app1>  <app2> ...
$ python manage.py migrate
```
간혹 앱을 명시해주지 않을 때 마이그레이션 파일이 안생기는 경우가 생기고, 그럴때 디비가 업데이트 되지 않던데
그 경우는 아닌가요?

다른 경우인가요?

**Comment by Luavis** [comment]
그런 문제 보다 굳이 제가 마이그레이션 파일을 생성하고 켤필요가 있나요? 
원래 마이그레이션 파일이라는게 모두가 같은 디비 형식을 추구하기 위하고 또한 단계별로 삭제를 할 수 있도록 제작된거 기 떄문에 ignore하면 안될거 같습니다.

**Comment by wikibootup** [comment]
넵 추가해주셔도 됩니다

저도 굳이 마이그레이션 파일을 만들고 싶지는 않은데요
처음에 적었듯이, 아직 프로그램이 안정화되지 않았다고 생각했었습니다

마이그레이션 파일은 production 단계에서부터 추가하길 권장하지만, 당시에 모델이 불안정하다고 생각했었거든요
