### ISSUE TITLE
captcha의 필요성

### ISSUE THREAD

**Issue by JunHyeongJeon** [ssu-see/see.ssu.ac.kr#49]
bot들이 가입하고 있습니다. 

captcha의 필요성이 느껴집니다.

**Comment by wikibootup** [comment]
확인! 오늘 8시 전까지..

**Comment by wikibootup** [comment]
폼 필드에서 동적으로 public key를 가져오는 부분이 걸리지만,
시간상 기능만 적용해 두었습니다

**Comment by Luavis** [comment]
이거 제가 진행 중입니다.

**Comment by Luavis** [comment]
recaptcha문제가 시급하면 지금 develop branch를 master랑 병합해도 되나요?

**Comment by wikibootup** [comment]
마스터 브랜치랑 병합해도 상관없어요 (프로그램이 안정적이라면 )
현재 서버에 레포는 develop 브랜치의 레포입니다

recaptcha는 구현되어 있습니다
더 나은 구현이 있다면 수정해도 좋습니다
하지만 교체할 정도라면 그럴 필요까지 있나 싶은 생각은 드네요(시간적인 낭비)

**Comment by Luavis** [comment]
뭔가 겹쳤네요... 그래서 커밋 다시 뺐어요
