### ISSUE TITLE
link board라는 제목말입니다

### ISSUE THREAD

**Issue by Luavis** [ssu-see/see.ssu.ac.kr#53]
이게 이름이 굉장히 어색해서 생각을 했었는데 생각해보니까 왠만한 사이트들은 links라거나 참조링크 뭐 이런식으로 제목을 넣어서 아마 이런식으로 바꿔보는게...

**Comment by wikibootup** [comment]
아, 찬성합니다

약간의 배경을 말씀드리면,,
이 홈페이지는 작년 11월 말에 전시회 작품으로 만들기 시작했습니다

미숙한 점이 많고, 그 부분은 `링크 보드`와 같은 네이밍에 있어서도 마찬가지입니다
이런 부분은 `표준적인 것으로, 보편적인 것으로` 자유롭게 수정해주셔도 무방할 것 같습니다

**Comment by Luavis** [comment]
알겠습니다
