### ISSUE TITLE
버그포인트

### ISSUE THREAD

**Issue by Luavis** [ssu-see/see.ssu.ac.kr#55]
rewrite화면에서 첨부파일이 안보임
iframe을 domain에 따라 필터링

**Comment by Luavis** [comment]
그리고 iframe과 첨부파일 병행시 버그가 있는거 같으니 확인해보겠습니다.

**Comment by wikibootup** [comment]
네 알겠습니다

그리고 링크보드 업데이트 후 트라비스 테스트 오류가 났네요
모델 구조가 바껴서 그런건지, 더이상 적용되지 않는 테스트인지 점검 부탁드립니다

**Comment by wikibootup** [comment]
더불어 귀찮겠지만, 업데이트시 가급적 '푸시'보다는 풀리퀘 던지고 받으시길 부탁드립니다
