### ISSUE TITLE
총체적인 리팩토링

### ISSUE THREAD

**Issue by wikibootup** [ssu-see/see.ssu.ac.kr#6]
현재의 서버단 코드는 현재의 기능에만 간신히 돌아가는 것 같습니다.
참 과거의 제가 작성했지만 안타깝게도 수많은 리팩토링을 필요로 할 것 같아요ㅋㅋㅋㅋㅋㅋ
중간에 합쳐서 작업 중이신 `luavis` 공동 작업자 분들에게 사과의 말씀을 드리며
추후에 총체적인 리팩토링을 하도록 하겠습니다. 수정 환영합니다!

**Comment by Luavis** [comment]
엎어가면서 적당히 새로운 기능도 구상해서 넣어야하는데...
